### ISSUE TITLE
Flashing when mouse moving

### ISSUE THREAD

**Issue by EiEddie** [arijit79/minus#120]
**Describe the bug**
when I move my mouse on the terminal, pager is flashing.

**To Reproduce**
code as follows:

```rust
use std::fmt::Write;
use minus::{self, Pager};

fn main() -> Result<(), minus::MinusError> {
	let mut out = Pager::new();

	write!(out, "{}\n", "hello world ".repeat(1000))?;

	minus::page_all(out)?;

	Ok(())
}
```

and config on `Cargo.toml` is:

```toml
minus = { version = "5.5.1", default-features = false, features = [
	"static_output",
] }
```

run `cargo run` and move the mouse on terminal.

**Expected behavior**
it should not be flashing

**Screenshots**
![minus](https://github.com/arijit79/minus/assets/55616830/5fc11778-0622-4f0a-9683-b32f2eb3a6a7)

**Desktop:**
 - WSL, Ubuntu 22.04.2 LTS
- Windows Terminal
- zsh

**Something else**
I feel like I'm going blind...

**Comment by arijit79** [comment]
Can you reproduce it on the latest main because I can't reproduce it on it.

**Comment by EiEddie** [comment]
**YES!**

first, I do:
```shell
cargo new test-minus
cd test-minus
cargo add minus --features static_output
```
and this is my test:
```rust
// src/main.rs
use std::fmt::Write;
use minus::{self, Pager};

fn main() -> Result<(), minus::MinusError> {
        let mut out = Pager::new();

        write!(out, "{}\n", "hello world ".repeat(1000))?;

        minus::page_all(out)?;

        Ok(())
}
```
```toml
# Cargo.toml

[package]
name = "test-minus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minus = { version = "5.5.1", features = ["static_output"] }
```
and result have the same wrong, the pager is flushing.

then, I do
```shell
git clone https://github.com/arijit79/minus.git
cd minus
cargo r --example static --features="static_output"
```
and unluckily, same wrong
![minus](https://github.com/arijit79/minus/assets/55616830/74083eb3-ca4c-4b24-b6aa-5ab70290fc01)
