### ISSUE TITLE
Static (page_all) output is breaking zsh

### ISSUE THREAD

**Issue by sergiimk** [arijit79/minus#47]
Thank you for your work on this crate. I just gave `4.0.0-alpha1` version a try.

Pagination works as expected with a few minor (unrelated) issues:
- I expected space bar to be same as PgDn just like in `less`
- Search does not seem to navigate to the first/next occurence
- Highlighting of search result seems to break colors of the text being highlighted

But the main issue is that after I exit my program every mouse movement in the terminal window is causing some garbage output:
![image](https://user-images.githubusercontent.com/204914/124206541-75bae980-da98-11eb-98bb-d28989987e1d.png)

It's quite hard to recover the terminal session after this. 

Happy to help to test potential fixes or help narrow down what's causing this.

**Comment by arijit79** [comment]
Could you share a little bit of code what you have tried to implement?

By the thanks for putting up this issue.

**Comment by sergiimk** [comment]
The issue is reproducible for me even with this basic example:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minus = { version="4.0.0-alpha1", features=["static_output", "search"] }
```

```rust
// main.rs
use std::io::Write;

fn main() {
    let mut pager = minus::Pager::new().unwrap();

    writeln!(pager, "{}", "Hello, world!\n".repeat(500)).unwrap();

    minus::page_all(pager).unwrap();
}
```
