### ISSUE TITLE
Feeding minus with text from a network call results in corrupted text until resizing

### ISSUE THREAD

**Issue by Kinchkun** [arijit79/minus#66]
**Describe the bug**

Hi,

I'm using reqwest and tokio to make an async network call. Utilizing the `stream` feature of reqwest I'm reading chunks of the response text and `write!` it into minus using the `dynamic_paging` feature.

Then the text, line numbers and so forth gets corrupted until I resize the terminal window, which (I assume) causes a refresh of the view.

**To Reproduce**

```rust
use bstr::ByteSlice;
use bytes::Bytes;
use minus::LineNumbers;

#[tokio::main]
async fn main() {
    use futures::StreamExt;
    use minus::{dynamic_paging, MinusError, Pager};
    use std::fmt::Write;
    use tokio::{join, task::spawn_blocking};

    let pager = Pager::new();
    pager.set_line_numbers(LineNumbers::Enabled).unwrap();

    let task = async {
        let mut pager = pager.clone();
        let client = reqwest::Client::default();
        let mut stream = client.get("https://www.google.de/")
            .send()
            .await
            .unwrap()
            .bytes_stream();

        while let Some(chunk) = stream.next().await {
            let bytes: Bytes = chunk.unwrap();
            let text = bytes.to_str_lossy().to_string();
            write!(pager, "{}", text).unwrap();
        }
        Result::<_, MinusError>::Ok(())
    };

    let pager = pager.clone();
    let (res1, res2) = join!(spawn_blocking(move || dynamic_paging(pager)), task);
    res1.unwrap().unwrap();
    res2.unwrap();

}
```

Cargo.toml
```toml
[package]
name = "minus-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.10", features = ["stream"] }
minus = { version = "5", features = ["dynamic_output", "search"] }
tokio = { version = "1.17.0", features = ["full"] }
futures = "0.3.21"
anyhow = "1.0.56"
bytes = "1.1.0"
bstr = "0.2.17"
```

**Screenshots**

This is the immediate result:

![image](https://user-images.githubusercontent.com/8901105/160925391-ff276871-419a-43f0-b9d0-7ab90d479782.png)

As you can see, the line numbering is wrong and the content ins't correctly display. However, if I now resize the terminal everything is fine:

![image](https://user-images.githubusercontent.com/8901105/160925619-cfa62711-fb9f-4c11-811e-c42ef9f21697.png)

**Desktop:**
 - OS: macOS 12.2.1
- Terminal: Iterm and the native terminal.app
- Shell: zsh
- `minus` Version: 5.0.1

**Additional context**

When I don't stream the text-chunks but instead using the `text` method from reqwest, which loads the complete text into a single string with a single `write!` it works like a charm.
